title: 'Iris Estival-David, site officiel'
default_lang: fr
author:
  name: 'Iris Estival-David'
  email: thimy.nya@gmail.com
taxonomies:
  - category
  - tag
  - month
metadata:
  description: 'Iris Estival-David, Site Officiel'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects:
  /changelog: /blog/the-urban-jungle
routes:
  /something/else: /blog/focus-and-blur
  '/another/one/(.*)': /blog/$1
blog:
  route: ''
